#!/bin/bash

# ================= HELP FUNCTION =================
print_help() {
    echo -e "${BLUE}======================================================================${NC}"
    echo -e "${YELLOW}               CUSTOM AUTOMATION & DEPLOYMENT TOOL (t)${NC}"
    echo -e "${BLUE}======================================================================${NC}"
    echo -e "Usage: t [COMMAND] [IP_SUFFIX] [FLAGS]"
    echo -e ""
    echo -e "${YELLOW}COMMANDS:${NC}"
    echo -e "  ${GREEN}deploy <IP>${NC}      Smart Build & Deploy (Alias: ${GREEN}td${NC})"
    echo -e "  ${GREEN}ssh <IP>${NC}         Auto-Root Login."
    echo -e "  ${GREEN}find [query]${NC}     Search your personal cheatsheet (Alias: ${GREEN}tf${NC})"
    echo -e "  ${GREEN}dnfupdate <IP>${NC}   Run DNF Update script on remote."
    echo -e "  ${GREEN}setpass [IP]${NC}     Update stored password for Bridge User (${BRIDGE_USER})."
    echo -e "                     (Optional IP allows validating the new password immediately)"
    echo -e "  ${GREEN}setroot <IP>${NC}     Sync Root password with Bridge password & enable Root Login."
    echo -e "  ${GREEN}readme${NC}           Show the documentation (README.md)."
    echo -e ""
    echo -e "${YELLOW}DATA SOURCE (for 'tf'):${NC}"
    echo -e "  File Path: ${WHITE}$CMD_LIBRARY${NC}"
    echo -e "  ${BLUE}Format:${NC}    Description | Command"
    echo -e "  ${BLUE}Example:${NC}   Find large files | find / -size +100M"
    echo -e ""
    echo -e "${YELLOW}ARGUMENTS & FLAGS:${NC}"
    echo -e "  ${WHITE}<IP>${NC}                 Smart IP Expansion (Default Base: ${BASE_IP}.${DEFAULT_SUBNET})"
    echo -e "      * Type ${GREEN}116${NC}     -> ${BLUE}192.168.78.116${NC}"
    echo -e "      * Type ${GREEN}77.116${NC}  -> ${BLUE}192.168.77.116${NC}"
    echo -e ""
    echo -e "  ${WHITE}-v <version>${NC}         Specific Version Control"
    echo -e "      * ${BLUE}Client:${NC} Sets build env (e.g., -v 9.3.5)"
    echo -e "      * ${BLUE}DB:${NC}     Syncs specific folder (e.g., -v 935)"
    echo -e ""
    echo -e "${YELLOW}USAGE EXAMPLES:${NC}"
    echo -e "  ${GREEN}td 116${NC}              Deploy current project to 192.168.78.116"
    echo -e "  ${GREEN}td 116 -v 9.3.5${NC}     Deploy version 9.3.5 explicitly"
    echo -e "  ${GREEN}td 77.116${NC}           Deploy to custom subnet 192.168.77.116"
    echo -e "  ${GREEN}tf docker${NC}           Search cheatsheet for 'docker' commands"
    echo -e "  ${GREEN}t setpass${NC}           Reset the saved password for user '$BRIDGE_USER'"
    echo -e "  ${GREEN}t setroot 11${NC}        Set Root password on .11 to match Sunbird's"
}