#!/bin/bash

# ================= HELP FUNCTION =================
print_help() {
    echo -e "${BLUE}======================================================================${NC}"
    echo -e "${YELLOW}               CUSTOM AUTOMATION & DEPLOYMENT TOOL (t)${NC}"
    echo -e "${BLUE}======================================================================${NC}"
    echo -e "Usage: t [COMMAND] [IP_SUFFIX] [FLAGS]"
    echo -e ""
    echo -e "${YELLOW}CORE COMMANDS:${NC}"
    echo -e "  ${GREEN}deploy${NC}      Smart Build & Deploy (Alias: ${GREEN}td${NC})"
    echo -e "  ${GREEN}find${NC}        Search Cheatsheet (Alias: ${GREEN}tf${NC})"
    echo -e "  ${GREEN}ssh${NC}         Auto-Root Login / Key Install"
    echo -e "  ${GREEN}viewlog${NC}     Remote Log Viewer (Alias: ${GREEN}log${NC})"
    echo -e "  ${GREEN}readme${NC}      Show Docs (Internal or Local Path)"
    echo -e ""
    echo -e "${YELLOW}DEVELOPMENT:${NC}"
    echo -e "  ${GREEN}edit${NC}        Remote File Editor (Alias: ${GREEN}te${NC})"
    echo -e "                 ${BLUE}Supports SSHFS mounting for IDEs${NC}"
    echo -e ""
    echo -e "${YELLOW}ADMIN & INIT:${NC}"
    echo -e "  ${GREEN}initvm${NC}      Full Init: Root Setup + Postgres Trust + Tomcat Debug"
    echo -e "  ${GREEN}rootsetup${NC}   Enable Root SSH (w/ Password Sync Prompt)"
    echo -e "  ${GREEN}pgtrust${NC}     Whitelist Local IP in Remote Postgres"
    echo -e "  ${GREEN}tomcatsetup${NC} Enable Remote Debug (Port 8000)"
    echo -e "  ${GREEN}dnfupdate${NC}   Run DNF Update Script"
    echo -e ""
    echo -e "${YELLOW}CONFIGURATION:${NC}"
    echo -e "  ${GREEN}setpass${NC}     Update Bridge User Password"
    echo -e "  ${GREEN}setlogviewer${NC} Switch Log Viewer (lnav/glogg)"
    echo -e ""
    echo -e "${YELLOW}DEPLOYMENT LOGIC (td):${NC}"
    echo -e "  The tool detects the target based on files in your current directory:"
    echo -e "  ${BLUE}1. Server Mode:${NC}   Folder must be named ${WHITE}'server'${NC} AND contain ${WHITE}'./dcTrackApp'${NC}"
    echo -e "  ${BLUE}2. Client Mode:${NC}   Path must contain ${WHITE}'client'${NC} AND contain ${WHITE}'./package.json'${NC}"
    echo -e "  ${BLUE}3. Database Mode:${NC} Must contain ${WHITE}'./src/files/opt/raritan/liquibase/changesets'${NC}"
    echo -e ""
    echo -e "${YELLOW}FLAGS:${NC}"
    echo -e "  ${WHITE}-v, --version <str>${NC}   Override version (Deploy only)"
    echo -e "  ${WHITE}-l, --limit <num>${NC}     Limit search results (Find only)"
}